### PR TITLE
Allow output directly to buffer

### PR DESCRIPTION
**Pull request by iudex-**
I would love to be able to save the merged pdf directly to a buffer

pdfjs supports it as [`asBuffer()`](https://github.com/rkusa/pdfjs/blob/master/docs/document.md#asbufferopts-callback), so i just added it

### CODE REVIEW

**Review by mojoaxel — APPROVED** [review]
LGTM

**Comment by mojoaxel** [comment]
@iudex- Thx!

**Comment by iudex-** [comment]
That was quick :relaxed: 
Thank you for the library!

**Comment by FaridSafi** [comment]
Thank you for your work guys. Looking forward to the new version with `saveAsBuffer`.

**Pull request merged**
